# Generated by Django 3.1.1 on 2021-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210524_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('ONE', '1'), ('TWO', '2'), ('THR', '3'), ('FOU', '4'), ('FIV', '5'), ('SIX', '6'), ('SEV', '7'), ('EIG', '8'), ('NIN', '9'), ('TEN', '10'), ('ELV', '11'), ('TWE', '12'), ('THI', '13')], default=('ONE', '1'), max_length=20),
        ),
    ]
